### ISSUE TITLE
Readme example doesn't compile on 1.30.1 stable

### ISSUE THREAD

**Issue by itamar8910** [vickenty/lang-c#2]
When trying to compile the example in the readme:
`println!("{:?}", parse(&config, "example.c"));`

I'm getting the following error:
`the size for values of type 'str' cannot be known at compilation time`

This is resolved when passing a String reference instead of an str:
`println!("{:?}", parse(&config, &"example.c".to_string()));`

**Comment by vickenty** [comment]
Thanks!
