### ISSUE TITLE
Compound literals do not work

### ISSUE THREAD

**Issue by robbym** [vickenty/lang-c#21]
[Compound literals](https://en.cppreference.com/w/c/language/compound_literal) do not seem to work.

Test preprocessed C file:
```c
# 1 "test.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "test.c"
typedef struct
{
    int value;
} test_t;

void test(test_t* myStruct)
{
    *myStruct = (test_t) {.value = 1};
}
```

Error:
```
SyntaxError {
    source: --- see above ---,
    line: 12,
    column: 26,
    offset: 173,
    expected: {
        "<",
        "!=",
        "*=",
        "%=",
        "&",
        "==",
        ">",
        "<<",
        "&&",
        ">>",
        "u8",
        "[",
        "~",
        ">=",
        "*",
        "/",
        "++",
        "->",
        "--",
        "+",
        "<<=",
        ";",
        "?",
        "|=",
        "[_a-zA-Z]",
        ">>=",
        "[uUL]",
        "^=",
        ",",
        ".",
        "!",
        "||",
        "(",
        "-=",
        "\"",
        "/=",
        "<=",
        "^",
        "%",
        "=",
        "+=",
        "&=",
        "|",
        "-",
    },
}
```

**Comment by vickenty** [comment]
Thanks. 

Two grammar bits seem to be not working properly:
- typedef is not recognized as type name
- designators

**Comment by robbym** [comment]
> 
> 
> Thanks.
> 
> Two grammar bits seem to be not working properly:
> 
>     * typedef is not recognized as type name
> 
>     * designators

Are those two grammar issues related to the compound literals issue? Or are you referring to https://github.com/vickenty/lang-c/issues/23?

**Comment by vickenty** [comment]
I was referring to this issue. In a test I did, `(test_t) {..` didn't parse just as you reported, but `(struct test_t) {...` seemed to progress further and fail on the designator. I didn't see your PR yet when I wrote that, and I still need to go through it.
