### ISSUE TITLE
Parse error in struct typedef

### ISSUE THREAD

**Issue by theduke** [vickenty/lang-c#35]
```c
typedef struct mi_heap_area_s {
  size_t x;
} mi_heap_area_t;

```

==> `unexpected token at line 9 column 3, expected '<typedef_name>', '}'`

Notice also the wrong line number!

Curiously, this works: 

```c
typedef struct mi_heap_area_s {
  void* x;
} mi_heap_area_t;
```

**Comment by vickenty** [comment]
Thanks for the report!

The parse error should be fixed by 3c8d0f489f2ad9453144a915ad5f92aac2320fce.

Line numbers are a known issue: they correspond to the source after preprocessor expansion, rather than the original input, so not very helpful.
