### ISSUE TITLE
Consider keeping a line number or something in the Span object

### ISSUE THREAD

**Issue by omarandlorraine** [vickenty/lang-c#38]
I've started a [crummy linter](https://github.com/omarandlorraine/lowlint). Not much good yet; it's just got the one checker so far and that is the you're-actually-using-the-variable-before-it's-even-been-initialized checker. But it's finding problems where I put them, so.

The thing is I'd like to report to my end user something like "I found an issue on line 57". But information about line numbers is actually discarded by the time I figure out there's even a problem to report. I have reference to a Span object though, which so far as I can figure out, lets me know the (preprocessed) character count. I wonder if we can add the line number in there.

**Comment by vickenty** [comment]
There is a [helper module](https://docs.rs/lang-c/latest/lang_c/loc/index.html) that can convert byte offsets into file name and line number. The reason not to store this in the Span directly, is because there are a lot of spans in the AST tree, so it pays to keep these objects as small as possible.

**Comment by omarandlorraine** [comment]
Do you know how `get_location_for_offset` is meant to work?

As the first parameter I've tried passing the filename, and I've tried passing the file's contents. In both cases, it panics in my case with a message like the following

```
thread 'main' panicked at 'byte index 68 is out of bounds of `#include <stdio.h>
int main() {
        int i;
        putchar(i);
        int x = i;
}
`', library/core/src/str/mod.rs:107:9
```

The documentation is a little unclear, but I figured out that `get_location_for_offset` does *not* expect the first parameter to be a file name, but the contents of the file. Do I need to expand the `#include`s and other directives myself?
