### ISSUE TITLE
Convert span offsets to the one in the pre pre-process file

### ISSUE THREAD

**Issue by HKalbasi** [vickenty/lang-c#43]
Is it possible to convert an `Span` of this library to a `(Filename, Span)` in the original files in the disk? I'm trying to show some info about the C code using [ariadne](https://docs.rs/ariadne/latest/ariadne/) crate, and I'm currently using the pre-processed text using the `source` field of `Parse`, but I would like to do that conversion to make the spans show correct line number and file names.

**Comment by vickenty** [comment]
Sorry for the late reply.

I don't think there is a way to extract original byte positions of tokens - the external preprocessor only provides line numbers. There is a way to map spans to filename and line number though, see https://docs.rs/lang-c/latest/lang_c/loc/fn.get_location_for_offset.html
