### ISSUE TITLE
Chained LogicalAnds are parsed incorrectly

### ISSUE THREAD

**Issue by jgallagher** [vickenty/lang-c#6]
Hi - thanks a lot for this crate, it is really great! I did run in to one bug; it looks like chained `&&` operators are not parsed correctly. An example:

```rust
extern crate lang_c;

use lang_c::driver::{Config, parse_preprocessed};

fn main() {
    let parse = parse_preprocessed(&Config::default(), "
int foo(void) {
    return 1 && 2 && 3;
}".to_string()).unwrap();
    println!("{:?}", parse);
}
```

Trimming the output down substantially and to just the return, the resulting parsed ast is:

```
Return(Some(BinaryOperator(BinaryOperatorExpression {
  operator: LogicalAnd,
  lhs: Constant(Integer(Integer { base: Decimal, number: "1" })),
  rhs: BinaryOperator(BinaryOperatorExpression {
    operator: BitwiseAnd,
    lhs: Constant(Integer(Integer { base: Decimal, number: "2" })),
    rhs: UnaryOperator(UnaryOperatorExpression {
      operator: Address,
      operand: Constant(Integer(Integer { base: Decimal, number: "3" })),
    }),
  }),
})))
```

The second `&&` is being broken up into a bitwise-and followed by an address-of, as though the input were:

```c
return (1 && (2 & (&3));
```

but I believe it should be parsed as though it were

```c
return (1 && 2) && 3;
```

Adding parens around either `1 && 2` or `2 && 3` does not have this problem. I was also not able to recreate it with other infix operators, although I'm sure I didn't try all of them.

**Comment by vickenty** [comment]
Thanks!
